export interface user {
    id: number,
    addressContact: string,
    addressHouse: string,
    addressWork: string,
    amphurContact: string,
    amphurHouse: string,
    auditorVf: string,
    created: Date,
    deleted: number,
    districtContact: string,
    districtHouse: string,
    districtWork: string,
    educateDegree: string,
    email: string,
    emailWork: string,
    firstName: string,
    lastName: string,
    manualVf: string,
    mobileNumber: string,
    mobileWork: string,
    mooContact: string,
    mooHouse: string,
    mooWork: string,
    occupation: string,
    password: string,
    perId: string,
    phoneNumber: string,
    postDelivery: string
    prefixName: string
    provinceContact: string
    provinceHouse: string
    provinceWork: string
    roadContact: string
    roadHouse: string
    roadWork: string
    role: string
    soiContact: string
    soiHouse: string
    soiWork: string
    username: string
    workPlace: string
    zipCodeContact: string
    zipCodeHouse: string
    zipCodeWork: string
}